### ISSUE TITLE
Create DB and BE architecture

### ISSUE THREAD

**Issue by rostag** [rostag/bigpolicy_eu#8]
- [x] Leaders (impl. by #29)
- [x] Projects (impl. by #32)
- [x] Tasks (impl. by #39 )
- [x] User Profile (impl. by #35 )
- [x] User Authentication (impl. by #35 )

**Comment by Prokop** [comment]
@lepta-ua всі елементи враховані?

**Comment by rostag** [comment]
Implemented. Closing
